# Generated by Django 3.2.5 on 2021-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='Images'),
            preserve_default=False,
        ),
    ]
